# Generated by Django 6.0.4 on 2026-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skills_alter_projeto_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Tecnologias',
            new_name='Tecnologia',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
